=== kuzmann/PF_Breakout/game.dtd
<?xml version="1.0" encoding="iso-8859-1"?>

<!ELEMENT game (gamer)*>

<!ELEMENT gamer (name, play, performance)>

<!ATTLIST gamer id ID #REQUIRED>
<!ELEMENT name (#PCDATA)>

<!ELEMENT play (level, points)>
<!ELEMENT level (#PCDATA)>
<!ELEMENT points (#PCDATA)>

<!ELEMENT performance (win, loss, bestpoints)>
<!ELEMENT win (#PCDATA)>
<!ELEMENT loss (#PCDATA)>
<!ELEMENT bestpoints (#PCDATA)>

=== kuzmann/PF_Breakout/game.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE game SYSTEM "game.dtd">


<game>

	<gamer id="id1">
		<name>Anna</name>
		<play>
			<level>2</level>
			<points>50</points>
		</play>
		<performance>
			<win>3</win>
			<loss>1</loss>
			<bestpoints>100</bestpoints>
		 </performance>
	</gamer>
	
	<gamer id="id2">
		<name>Jasper</name>
		<play>
			<level>5</level>
			<points>100</points>
		</play>
		<performance>
			<win>15</win>
			<loss>1</loss>
			<bestpoints>120</bestpoints>
		 </performance>
	</gamer>
	
</game>
